# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-08-14 07:45
from __future__ import unicode_literals

from django.db import migrations
from ..models import Dashboard


def set_dashboard_new_public(apps, schema_editor):
    Dashboard.objects.filter(public='all').update(
        new_public={'all': True, 'org': False, 'url': False})
    Dashboard.objects.filter(public='org').update(
        new_public={'all': False, 'org': True, 'url': False})
    Dashboard.objects.filter(public='url').update(
        new_public={'all': False, 'org': False, 'url': True})


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0028_auto_20180814_0045'),
    ]

    operations = [
         migrations.RunPython(set_dashboard_new_public),
    ]
