# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-08-14 08:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0029_set_new_public'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboard',
            name='public',
        ),
        migrations.RenameField(
            model_name='dashboard',
            old_name='new_public',
            new_name='public',
        ),
    ]
